backend:
  name: github
  branch: dev
  repo: mikewgd/mikewgd

media_folder: static/img
public_folder: /img

collections:
  -
    name: entries
    label: 'Portfolio Entries'
    folder: src/pages/portfolio/entries
    create: true
    slug: 'portfolio/{{slug}}'
    editor:
      preview: false
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "src/pages/portfolio/entry.js"}
      -
        label: Title
        name: title
        widget: string
      -
        label: 'Cover Image'
        name: coverImage
        widget: image
        allow_multiple: false
      -
        label: Blurb
        name: blurb
        widget: text
      -
        label: Description
        name: description
        widget: markdown
      -
        label: Entry URL
        name: entryUrl
        widget: string
        required: false
      -
        label: Tags
        name: tags
        widget: select
        multiple: true
        options:
          - Vue.js
          - SCSS/CSS
          - ES6
          - React.js
          - Contentful
          - Angular.js
          - Stylus/CSS
          - Node.js
          - MySQL
          - jQuery
          - Webpack
          - Contentful UI Ext
          - Paper.js          
          - AWS
          - Gulp
          - Vanilla JS
          - PHP
      - label: "Media"
        name: "media"
        widget: "file"
        required: false
        media_library:
          config:
            multiple: true
      -
        label: "Created"
        name: "created"
        widget: "datetime"
  -
    label: Pages
    name: pages
    files:
      - 
        label: 'Portfolio Page'
        name: portfolio
        file: src/pages/portfolio/index.md
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "src/pages/portfolio/index.js"}
          -
            label: 'Page Header'
            name: pageHeader
            widget: markdown
      -
        label: 'About Page'
        name: about
        file: src/pages/about/index.md
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "src/pages/about/index.js"}
          -
            label: 'Page Header'
            name: pageHeader
            widget: markdown
          -
            label: Body
            name: body
            widget: markdown
      -
        label: 'Home Page'
        name: home
        file: src/pages/index.md
        fields:
          - 
            label: 'Layout'
            name: layout
            widget: hidden
            default: 'blog'
          -
            label: 'Page Header'
            name: pageHeader
            widget: markdown
          -
            label: 'Entries Header'
            name: entryHeader
            widget: string
