backend:
  name: github
  branch: dev
  repo: mikewgd/mikewgd

media_folder: static/img
public_folder: /img

collections:
  -
    name: entries
    label: 'Portfolio Entry'
    folder: src/pages/portfolio/entry
    create: true
    slug: 'portfolio/{{slug}}'
    editor:
      preview: false
    fields:
      -
        label: 'Template Key'
        name: 'templateKey'
        widget: 'hidden'
        default: 'src/pages/portfolio/entry.js'
      -
        label: Title
        name: title
        widget: string
      -
        label: Blurb
        name: blurb
        widget: text
      -
        label: Body
        name: body
        widget: markdown
      -
        label: Entry URL
        name: entryUrl
        widget: string
        required: false
      -
        label: Tags
        name: tags
        widget: select
        multiple: true
        options:
          - Vue.js
          - SCSS/CSS
          - ES6
          - React.js
          - Contentful
          - Angular.js
          - Stylus/CSS
          - Node.js
          - MySQL
          - jQuery
          - Webpack
          - Contentful UI Ext
          - Paper.js          
          - AWS
          - Gulp
          - Vanilla JS
          - PHP
      -
        label: 'Media'
        name: 'media'
        widget: 'list'
        required: false
        fields:
          -
            label: Thumb
            name: 'thumb'
            widget: file
            media_library:
              config:
                multiple: false
          -
            label: 'Type'
            name: 'mediaType'
            widget: 'select'
            options: [
              'video',
              'article',
              'image',
            ]
          -
            label: 'Url'
            name: 'mediaUrl'
            widget: string
      -
        label: 'Created'
        name: 'created'
        widget: 'datetime'
  -
    label: Pages
    name: pages
    files:
      - 
        label: 'Portfolio Page'
        name: portfolio
        file: src/pages/portfolio/index.md
        slug: '/portfolio'
        fields:
          -
            label: 'Page Header'
            name: pageHeader
            widget: markdown
      -
        label: 'About Page'
        name: about
        file: src/pages/about/index.md
        fields:
          -
            label: 'Page Header'
            name: pageHeader
            widget: markdown
          -
            label: Body
            name: body
            widget: markdown
          -
            label: 'Social Links'
            name: 'socialLinks'
            widget: 'list'
            fields:
              -
                label: 'Url'
                name: 'socialUrl'
                widget: string
              -
                label: 'Type'
                name: 'socialType'
                widget: 'select'
                options: [
                  'facebook',
                  'instagram',
                  'github',
                  'linkedin',
                ]
      -
        label: 'Home Page'
        name: home
        file: src/pages/index.md
        fields:
          -
            label: 'Page Header'
            name: pageHeader
            widget: markdown
          -
            label: 'Body'
            name: body
            widget: markdown
